### ISSUE TITLE
Store the user's metrics (speed and accuracy)

### ISSUE THREAD

**Issue by SeanMarkWD** [SeanMarkWD/Speed-Typing-Test#13]
Using the browser's local storage, we can store the user's metrics (speed and accuracy). Local storage allows us to save data that persists even after the page is refreshed. This way, we can keep track of the user's performance over time.

**Comment by SeanMarkWD** [comment]
Steps to Incorporate the Enhancement
Calculate and Store Metrics: Update the displayResults function to store the calculated metrics in local storage.
Retrieve and Display Stored Metrics: Retrieve the stored metrics and display them to the user.

**Comment by SeanMarkWD** [comment]
Explanation
Store Metrics:

storeMetrics(wpm, accuracy): Stores the metrics in local storage with a timestamp.
Display Stored Metrics:

displayStoredMetrics(): Retrieves and displays the stored metrics from local storage.
Invoke Display on Load:

displayStoredMetrics() is called when the page loads to display previously stored metrics.

**Comment by SeanMarkWD** [comment]
Seeing an error if I check Chrome DevTools:

app.js:137 Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at displayStoredMetrics (app.js:137:34)
    at setupTypingTest (app.js:144:5)
    at window.onload (app.js:151:5)
    
    This typically means that the element with the ID metricsDisplay is not being found in the DOM. This typically happens if the element is not present in the HTML or if the JavaScript runs before the element is added to the DOM.

**Comment by SeanMarkWD** [comment]
Ensure HTML Contains the metricsDisplay Element
<div id="metricsDisplay"></div>

**Comment by SeanMarkWD** [comment]
Explanation
HTML:

The metricsDisplay element is added to the HTML, ensuring it is present when the JavaScript runs.
JavaScript:

The metricsDisplay element is correctly referenced, and its content is updated in the displayStoredMetrics function.
Metrics are stored in local storage and displayed when the page loads and when a test is completed.
